### ISSUE TITLE
Random Crash while creating pulseAnimationGroup

### ISSUE THREAD

**Issue by yzhong52** [TransitApp/SVPulsingAnnotationView#12]
And a while ago, we notice this bug while opening a map from our app. The app crashes on some random line of code in the following function for creating a animation group. 

```
- (CAAnimationGroup*)pulseAnimationGroup {
    if(!_pulseAnimationGroup) {
        _pulseAnimationGroup = [CAAnimationGroup animation];
        _pulseAnimationGroup.duration = self.outerPulseAnimationDuration + self.delayBetweenPulseCycles;
        _pulseAnimationGroup.repeatCount = INFINITY;
        ... and a lot more settings
    }
}
```

The problem is probably because this function is used in a secondary thread. Whatever code within `if(!_pulseAnimationGroup){ ... }` could be executed in different threads concurrently and it may result in some random crashes. 

```
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^(void) {
    if(self.delayBetweenPulseCycles != INFINITY) {
        CAAnimationGroup *animationGroup = self.pulseAnimationGroup;      
        dispatch_async(dispatch_get_main_queue(), ^(void) {
            [_colorHaloLayer addAnimation:animationGroup forKey:@"pulse"];
        });
    }
});
```

I am not 100% sure about the comments above. But please fix it if it is the case. But no matter what, it must bug somewhere else if not here.

**Comment by tedlee** [comment]
+1 I've seen this happen sporadically in our app. I'm not able to consistently reproduce it.
Did you find a fix?

@samvermette do you guys see this crash happen occasionally in Transit App?

**Comment by yzhong52** [comment]
Nice to know that someone finally notice the same issue! Yay, I think a simple fix is just to remove the [lazy initialization](http://stackoverflow.com/questions/10739726/when-to-use-lazy-instantiation-in-ios) for `pulseAnimationGroup` or make sure it is being called in the main thread whichever way you prefer.

**Comment by johnnyshankman** [comment]
I just opened another issue for this. Can we please make a PR for the fix @yzhong52 ?

**Comment by johnnyshankman** [comment]
https://github.com/TransitApp/SVPulsingAnnotationView/issues/17

**Comment by yzhong52** [comment]
Hello @johnnyshankman, I think I should have submit a PR at the time when I open this issue. But now it has been too long and I don't remember all the details and we are no longer using this library in our app. I am not too confident to submit a good patch for it without enough testing right now. If you are still interested in using this library, could you take a step and make the changes and submit the PR after you have tested with your app?

**Comment by johnnyshankman** [comment]
@yzhong52 No problem man!

If the solution really is as easy as removing the lazy instantiation conditional surrounding the code block I could def make the PR for it. I've edited my version in my project to do exactly that and don't have any crashes yet, but the crashes themselves are so arbitrary and spread out that I'll need some time to come up with some testing for this to prove it works.

**Comment by yzhong52** [comment]
Nice! I think another option that you could try is to change the property to `atomic`. That may fix the issue as well. But you do need more testing to confirm that. Good luck! Would love to see you merge requesting coming in :)

**Comment by johnnyshankman** [comment]
Ill give both a shot, thanks for the info man!

**Comment by yzhong52** [comment]
No problem.

**Comment by johnnyshankman** [comment]
Hm I can't find a consistent way to create the bug. @yzhong52 do you remember an easy and reliable setup? I try changing the color back and force on loop and suddenly it never breaks -____-

**Comment by nmtitov** [comment]
I am seeing this bug when I change image and annotationColor properties

**Comment by yzhong52** [comment]
@johnnyshankman how about this, put a random sleep inside this if statement. I think it should increase the chances: 

    if(!_pulseAnimationGroup) { ... }

**Comment by johnnyshankman** [comment]
I've recently gotten a lot of stability by ensuring I always change the pulse color before the annotation.

Curious if anyone's been getting the same behavior

**Comment by johnnyshankman** [comment]
@nmtitov in which order do you set them? I wonder if the annotation color needs to always be set last because of this bug.

**Comment by romanfrozzt** [comment]
Hey guys, I'm also experiencing this crash in my app. @yzhong52 I suspect running in a secondary thread may be the reason for this.
I'm using a fork of this repo, so I'm going to try to fix that and see if I will ever get report about this crash again. Will make a PM as soon as / if it's gone. Cheers guys!
